# Python core libraries
import sys
import os

# PyQT5 files
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QLabel, QWidget, QGridLayout, QLineEdit, QSystemTrayIcon
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon

# Window file generated by QT Designer
from gui.window_ui import Ui_MainWindow

from user import User

if __debug__:
    from gui.logger_ui import LoggerDialog


class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setupUi(self)

        iconPath = os.path.join(os.path.dirname(__file__), 'assets/nautiljon_icon.ico')
        self.systemtray_icon = QSystemTrayIcon(QIcon(iconPath))
        self.systemtray_icon.show()

        self.user = User()

        self.connectError.setVisible(False)
        self.connectSuccess.setVisible(False)

    def onConnect(self, checked):
        username = self.usernameInput.text()
        password = self.passwordInput.text()

        if not self.user.connect(username, password):
            self.loginForm.setVisible(True)
            self.connectError.setVisible(True)
            self.connectSuccess.setVisible(False)
        else:
            self.loginForm.setVisible(False)
            self.connectError.setVisible(False)
            self.connectSuccess.setVisible(True)

def main():
    app = QApplication(sys.argv)

    main_window = MainWindow()
    main_window.show()

    if __debug__:
        logger_window = LoggerDialog(main_window)
        logger_window.move(0, 0)
        logger_window.setGeometry(0, 0, 1000, 300)
        logger_window.show()

    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
